apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MHKGH/spring-petclinic-monolithic.git
    targetRevision: HEAD
    path: k8s  # The folder where your db.yml and petclinic.yml are
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true