apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: petclinic
  endpoints:
  - port: http
    path: /actuator/prometheus  # FIXED: changed 'Prometheus' to 'prometheus'
    interval: 30s
